### ISSUE TITLE
Math util

### ISSUE THREAD

**Issue by wbaik** [virgax7/PE#1]
Quick comment / recommendation...

In [utils](https://github.com/virgax7/PE/blob/master/src/mp/math_utils.py), looks like you're playing with prime numbers!

Please take a look at an efficient method to find primes: https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes
```
def prime_sieve(limit):
    prime = [True] * limit
    prime[0] = prime[1] = False

    for p, is_prime in enumerate(prime):
        if is_prime:
            yield p
            for n in range(p * p, limit, p):
                prime[n] = False
```

This is purely for an academic fun right?

**Comment by virgax7** [comment]
This is great! Thank you for the recommendation.

Yes, purely for academic fun

**Comment by virgax7** [comment]
this yield thing is pretty cool btw lol
