### ISSUE TITLE
Not pythonic q31?

### ISSUE THREAD

**Issue by wbaik** [virgax7/PE#2]
Hey, 

I know [Q.31](https://github.com/virgax7/PE/blob/master/src/questions-21-40/q31.py) works fine as is, but really feel un`pythonic`. `ans` might as well be just an int? So might as well wrap it in a wrapper function and have a `closure`?

**Comment by virgax7** [comment]
pull request :D  it, my codes been getting lazier and lazier lol

**Comment by wbaik** [comment]
Cool will do tonight, mate.

**Comment by virgax7** [comment]
take your time, but actually you can directly push, forgot about that XD

**Comment by wbaik** [comment]
@virgax7 No, XD I'd rather pull request
